### ISSUE TITLE
У цветных сообщений отображается знак параграфа в ВК

### ISSUE THREAD

**Issue by MelonHell** [Spliterash/VkChat#1]
![изображение](https://user-images.githubusercontent.com/53826469/104329847-77025500-54fe-11eb-9605-42ce23e0956c.png)

![изображение](https://user-images.githubusercontent.com/53826469/104329803-66ea7580-54fe-11eb-848b-c5a9318e7185.png)

**Comment by Spliterash** [comment]
Решили
